### PR TITLE
Web view screens

### PR DESCRIPTION
**Pull request by rjwills28**
I have re-formatted the internal web view versions of the machine status screens (by re-formatting the original OPI screens). 
I have also made some cosmetic changes to the header and footer.
Updates in reference to: https://github.com/dls-controls/machine-status/issues/14

### CODE REVIEW

**Comment by aawdls** [comment]
Also did you tweak the logo padding? I can't notice the difference from last time.

**Comment by rjwills28** [comment]
I did tweak the logo - I made it a bit smaller and added some padding around the sides. Do you see this and/or would you like more?

image

**Comment by rjwills28** [comment]
Also, what version of node did you need to build this? I don't think I changed versions but maybe I started with a different one.

**Comment by aawdls** [comment]
For node, I took the latest as of last week which is 16.14.2. My workstation has 10.24.0 as the system install which I found to be too old.

**Pull request merged**
