### PR TITLE
Hiding the path in the displayed url

### PR DESCRIPTION
**Pull request by rjwills28**
This change will mean that only https://xxxx.xxxx.ac.uk will be shown as the url.

### CODE REVIEW

**Comment by aawdls** [comment]
Will I still be able to show a certain opi by visiting the specific URL as before?

**Comment by rjwills28** [comment]
I've just tested this, i.e. running the web version of the application and adding _/json/ms_day/_ to the url and the answer is **no**, you would no longer be able to display a specific opi file from the URL. Is this something that we would require in the web version? Arguably we don't need this feature in the display version as the URL will never be visible.

**Comment by rjwills28** [comment]
I have found an alternative way of changing the displayed URL to something more readable for the machine status screens but still allow you to specify a path to show a certain OPI. Suggestion below:

Monitor display:
- Providing no path: "/" will redirect to the rotation with paths: "/day"," /week", "/fe1", "/fe2", "/message"
- Providing a path such as "/json/ms_day" will display the day view but this will be static (no rotation).

Web display
- Providing no path "/" will redirect to path "/machine-status" and will load the tabbed view to select the view to show.
- Specifying any other path, e.g. "/json/someJsonFile" will load that view.

**Comment by aawdls** [comment]
Thanks. This sounds better and will give the required flexibility, as I do think we will require to be able to naviagate to specific views.

**Pull request merged**
